[build]
  publish = "."  # Папка для публикации (корень проекта)
  functions = "netlify/functions"  # Папка с функциями
 

[functions]
  node_bundler = "esbuild" 
  function = "telegram_bot"
  runtime = "python-3.8"